version: '3'

services:
  mysql:
    image: mysql:5.7
    command: --innodb-use-native-aio=0
    container_name: full-cycle-mysql
    restart: always
    tty: true
    volumes:
      - ./mysql:/var/lib/mysql
    environment:
      - MYSQL_DATABASE=nodedb
      - MYSQL_ROOT_PASSWORD=root
    networks:
      - fullcyclenet

  nginx:
    build:
      context: ./nginx
      dockerfile: Dockerfile
    image: kotayz/nginx-full-cycle:latest
    container_name: full-cycle-nginx
    entrypoint: dockerize -wait tcp://node:3000 -timeout 20s nginx -g "daemon off";
    networks:
      - fullcyclenet
    ports:
      - 8080:80
    depends_on:
      - node

  node:
    build:
      context: ./node
      dockerfile: Dockerfile
    image: kotayz/node-full-cycle:latest
    container_name: full-cycle-node
    entrypoint: dockerize -wait tcp://mysql:3306 -timeout 20s node index.js
    networks:
      - fullcyclenet
    tty: true
    depends_on:
      - mysql

networks:
  fullcyclenet:
    driver: bridge